blueprint:
  name: "✨\U0001F4A1 Sun-aware Motion Light Control \U0001F3C3‍♂️☀️"
  description: "\U0001F4E6 [Version 1.0.1] Smart Light Control for Motion \U0001F3C3‍♂️.
    Turns on a light with adjustable brightness when motion is detected. Optionally,
    it can use different brightness levels depending on the sun's position \U0001F305."
  domain: automation
  source_url: https://github.com/r3mcos3/blueprints/blob/main/sun_aware_motion_light/sun_aware_motion_light.yaml
  author: r3mcos3
  homeassistant:
    min_version: 2025.12.0
  input:
    motion_sensor:
      name: "\U0001F3C3‍♂️ Motion Sensor"
      description: "The \U0001F3C3‍♂️ motion sensor that detects presence."
      selector:
        entity:
          domain:
          - binary_sensor
          device_class:
          - motion
          multiple: false
          reorder: false
    target_light:
      name: "\U0001F4A1 Target Light"
      description: "The \U0001F4A1 light or group of lights controlled by this automation."
      selector:
        target:
          entity:
          - domain:
            - light
    default_brightness:
      name: "\U0001F506 Default Brightness"
      description: "The \U0001F506 brightness percentage to use when sun-aware mode
        is disabled."
      default: 80
      selector:
        number:
          min: 0.0
          max: 100.0
          unit_of_measurement: '%'
          step: 1.0
          mode: slider
    sun_aware_settings:
      name: ☀️ Sun-aware Settings
      description: "Configure brightness levels \U0001F313 based on the sun's position
        ☀️\U0001F319."
      collapsed: true
      icon: mdi:weather-sunny
      input:
        sun_aware_enabled:
          name: ☀️ Sun-aware Mode
          description: "Enable \U0001F7E2 to use different brightness levels for day
            and night. If \U0001F534 disabled, a single brightness level is used."
          selector:
            boolean: {}
          default: true
        brightness_day:
          name: ☀️ Brightness (Day)
          description: The ✨ brightness percentage for when the sun ☀️ is up (only
            if sun-aware mode is enabled).
          default: 100
          selector:
            number:
              min: 0.0
              max: 100.0
              unit_of_measurement: '%'
              step: 1.0
              mode: slider
        brightness_night:
          name: "\U0001F319 Brightness (Night)"
          description: "The ✨ brightness percentage for when the sun \U0001F319 is
            down (only if sun-aware mode is enabled)."
          default: 10
          selector:
            number:
              min: 0.0
              max: 100.0
              unit_of_measurement: '%'
              step: 1.0
              mode: slider
    turn_off_delay:
      name: Turn-off delay
      description: The ⏱️ wait time in minutes before the light turns off after no
        motion is detected. Set to 0 for no delay.
      default: 5
      selector:
        number:
          min: 0.0
          max: 100.0
          step: 1.0
          unit_of_measurement: minutes
          mode: slider
trigger:
- platform: state
  entity_id: !input motion_sensor
  from: 'off'
  to: 'on'
  id: motion_on
- platform: state
  entity_id: !input motion_sensor
  from: 'on'
  to: 'off'
  id: motion_off
  for:
    hours: 0
    minutes: !input turn_off_delay
    seconds: 0
variables:
  sun_aware_enabled: !input sun_aware_enabled
action:
- choose:
  - conditions:
    - condition: trigger
      id: motion_on
    sequence:
    - choose:
      - conditions:
        - condition: template
          value_template: '{{ sun_aware_enabled }}'
        sequence:
        - choose:
          - conditions:
            - condition: state
              entity_id: sun.sun
              state: above_horizon
            sequence:
            - service: light.turn_on
              target: !input target_light
              data:
                brightness_pct: !input brightness_day
          default:
          - service: light.turn_on
            target: !input target_light
            data:
              brightness_pct: !input brightness_night
      default:
      - service: light.turn_on
        target: !input target_light
        data:
          brightness_pct: !input default_brightness
  - conditions:
    - condition: trigger
      id: motion_off
    sequence:
    - service: light.turn_off
      target: !input target_light
mode: restart
