- id: '1651867199741'
  alias: Verlichting - Motion WC
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.motion_wc_occupancy
  condition: []
  action:
  - if:
    - type: is_motion
      condition: device
      device_id: 5d7edd0dba517d1e6248c427036ef9f8
      entity_id: binary_sensor.motion_wc_occupancy
      domain: binary_sensor
    then:
    - type: turn_on
      device_id: 6c2f1fa3fe7a60a8e24ea6e380828587
      entity_id: switch.wc
      domain: switch
    else:
    - delay:
        hours: 0
        minutes: 3
        seconds: 0
        milliseconds: 0
    - type: turn_off
      device_id: 6c2f1fa3fe7a60a8e24ea6e380828587
      entity_id: switch.wc
      domain: switch
  mode: restart
- id: '1651867278786'
  alias: Verlichting - Motion Kelder
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.motion_kelder_occupancy
  condition: []
  action:
  - if:
    - type: is_motion
      condition: device
      device_id: 6a569df4bb8bf2af8035bc3fc0a1c00e
      entity_id: binary_sensor.motion_kelder_occupancy
      domain: binary_sensor
    then:
    - type: turn_on
      device_id: b321535cf6c225feba281c1049d33667
      entity_id: light.kelder
      domain: light
    else:
    - type: turn_off
      device_id: b321535cf6c225feba281c1049d33667
      entity_id: light.kelder
      domain: light
  mode: single
- id: '1651869469562'
  alias: Verlichting - Prullenbak
  description: ''
  trigger:
  - type: opened
    platform: device
    device_id: d6b807206713d4e9894e9890d5bfefee
    entity_id: binary_sensor.achter_deur_contact
    domain: binary_sensor
  condition:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  action:
  - service: light.turn_on
    data:
      brightness_pct: 100
    target:
      device_id:
      - ead4600643be65bf57ac2bf4230c6de3
      - e81bc8e9c660d0eed4b4bfada7e85bd0
  - delay:
      hours: 0
      minutes: 2
      seconds: 30
      milliseconds: 0
  - service: light.turn_off
    data: {}
    target:
      device_id:
      - ead4600643be65bf57ac2bf4230c6de3
      - e81bc8e9c660d0eed4b4bfada7e85bd0
  mode: restart
- id: '1651872263028'
  alias: Systeem - Volume Controller
  description: ''
  trigger:
  - platform: time
    at: '20:30:00'
    id: late
  - platform: time
    at: 08:30:00
    id: early
  condition: []
  action:
  - choose:
    - conditions:
      - condition: trigger
        id: early
      sequence:
      - service: media_player.volume_set
        data:
          volume_level: 0.6
        target:
          device_id:
          - 364c464e0e202bff3e0bde1d8437ec07
          - 299acf3ce36c8cb89e54dc1f5a3aaaae
          - 5dedfe783d0fd7c612b70a992eccf51b
          - 27429429865c131acfa167c2eaec8cee
          - 1874e2d9c1173fc75115fa99abaaf0c4
    - conditions:
      - condition: trigger
        id: late
      sequence:
      - service: media_player.volume_set
        data:
          volume_level: 0.2
        target:
          device_id:
          - 364c464e0e202bff3e0bde1d8437ec07
          - 27429429865c131acfa167c2eaec8cee
          - 299acf3ce36c8cb89e54dc1f5a3aaaae
          - 5dedfe783d0fd7c612b70a992eccf51b
          - 1874e2d9c1173fc75115fa99abaaf0c4
    default: []
  mode: single
- id: '1651910649614'
  alias: Remote - Schuur
  description: ''
  use_blueprint:
    path: EPMatt/ikea_e1812.yaml
    input:
      integration: Zigbee2MQTT
      controller_device: 1de969ae37f4a43f53b63eec5a22b433
      helper_last_controller_event: input_text.e1812_helper
      action_button_short:
      - service: light.toggle
        data: {}
        target:
          entity_id: light.schuur_groep
      controller_entity: sensor.remote_schuur_action
- id: '1651995638708'
  alias: Systeem - Zet Alarm Input Helper
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.oneplus_next_alarm
  condition: []
  action:
  - service: input_datetime.set_datetime
    data_template:
      entity_id: input_datetime.next_alarm_helper
      datetime: '{% if ''clock'' in (state_attr(''sensor.oneplus_next_alarm'', ''Package''
        )) %} {{ states(''sensor.oneplus_next_alarm'') |as_datetime |as_local }} {%
        endif %}'
  mode: single
- id: '1651995960366'
  alias: Verlichting - Wekker
  description: ''
  trigger:
  - platform: time
    at: input_datetime.next_alarm_helper
  condition:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  - condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'on'
  action:
  - service: light.turn_on
    data:
      brightness_pct: 15
    target:
      entity_id:
      - light.kast
      - light.woonkamer_spot_2
      - light.woonkamer_spot_4
      - light.woonkamer_spot_6
  - type: turn_on
    device_id: 4222716b45a1d39dbd565ee54535dac5
    entity_id: switch.keuken_schakelaar
    domain: switch
  mode: single
- id: '1651996343863'
  alias: Systeem - Backup
  description: ''
  trigger:
  - platform: time
    at: 03:00:00
  condition: []
  action:
  - service: backup.create
    data: {}
  mode: single
- id: '1652007654762'
  alias: Verlichting - Thuiskomst
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: zone.home
    above: '0'
  condition:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  action:
  - service: light.turn_on
    data:
      brightness_pct: 75
    target:
      entity_id:
      - light.woonkamer_spotjes
      - light.kast
      device_id: 4222716b45a1d39dbd565ee54535dac5
  - type: turn_on
    device_id: e5db3653dada9b0d11d0938e57e035b7
    entity_id: light.gang
    domain: light
    brightness_pct: 100
  - delay:
      hours: 0
      minutes: 5
      seconds: 0
      milliseconds: 0
  - type: turn_off
    device_id: e5db3653dada9b0d11d0938e57e035b7
    entity_id: light.gang
    domain: light
  mode: single
- id: '1652032478793'
  alias: Verlichting - Niemand Thuis, Alles Uit
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: zone.home
    below: '1'
  condition: []
  action:
  - service: light.turn_off
    data: {}
    target:
      entity_id: light.alles
  mode: single
- id: '1652120448569'
  alias: Verlichting - Overloop 10%
  description: ''
  trigger:
  - type: motion
    platform: device
    device_id: 127defd3005d56d0d76ce6fb80869602
    entity_id: binary_sensor.motion_trap_occupancy
    domain: binary_sensor
  - type: motion
    platform: device
    device_id: 127defd3005d56d0d76ce6fb80869602
    entity_id: binary_sensor.motion_trap_occupancy
    domain: binary_sensor
  condition:
  - condition: or
    conditions:
    - condition: device
      type: is_on
      device_id: cec7ba9131e5a3caafa4305e8cce223e
      entity_id: light.wled_elyza
      domain: light
    - condition: device
      type: is_on
      device_id: 37772b9b7040a174af7d0992802c61c7
      entity_id: light.wled_santi
      domain: light
  action:
  - service: light.turn_on
    data:
      brightness_pct: 10
    target:
      entity_id: light.overloop_spot_1
  - delay:
      hours: 0
      minutes: 5
      seconds: 0
      milliseconds: 0
  - service: light.turn_off
    data: {}
    target:
      entity_id: light.overloop_spot_1
  mode: restart
- id: '1652120649110'
  alias: Verlichting - Overloop 100%
  description: ''
  trigger:
  - type: motion
    platform: device
    device_id: 127defd3005d56d0d76ce6fb80869602
    entity_id: binary_sensor.motion_trap_occupancy
    domain: binary_sensor
  - type: motion
    platform: device
    device_id: 77afe808b9885c19a21e7c68ad9190fd
    entity_id: binary_sensor.motion_overloop_occupancy
    domain: binary_sensor
  condition:
  - condition: device
    type: is_off
    device_id: cec7ba9131e5a3caafa4305e8cce223e
    entity_id: light.wled_elyza
    domain: light
  - condition: device
    type: is_off
    device_id: 37772b9b7040a174af7d0992802c61c7
    entity_id: light.wled_santi
    domain: light
  action:
  - service: light.turn_on
    data:
      brightness_pct: 100
    target:
      entity_id: light.overloop
  - delay:
      hours: 0
      minutes: 5
      seconds: 0
      milliseconds: 0
  - service: light.turn_off
    data: {}
    target:
      entity_id: light.overloop
  mode: restart
- id: '1652204202294'
  alias: Verlichting - Sfeer Licht
  description: ''
  trigger:
  - platform: time
    at: '23:00:00'
    id: 'off'
  - platform: state
    entity_id:
    - sun.sun
    to: below_horizon
    id: 'on'
  condition: []
  action:
  - choose:
    - conditions:
      - condition: trigger
        id: 'on'
      sequence:
      - service: light.turn_on
        data: {}
        target:
          entity_id: light.sfeer_licht
    - conditions:
      - condition: trigger
        id: 'off'
      sequence:
      - service: light.turn_off
        data: {}
        target:
          entity_id: light.sfeer_licht
    default: []
  mode: single
- id: '1652288635900'
  alias: Rolluik - Santi
  description: ''
  trigger:
  - platform: time_pattern
    minutes: '30'
  condition:
  - condition: or
    conditions:
    - condition: state
      entity_id: weather.home
      state: sunny
    - condition: state
      entity_id: weather.home
      state: partlycloudy
  - condition: time
    after: '12:00:00'
    before: '22:00:00'
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
    - sat
    - sun
  action:
  - service: cover.close_cover
    data: {}
    target:
      device_id: 4296f897a44538a9b541d1a2bc0a2295
  mode: single
- id: '1652636355217'
  alias: Systeem - Update Beschikbaar
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.home_assistant_versions_dev_update_available
  condition: []
  action:
  - service: notify.mobile_app_oneplus
    data:
      message: Home Assistant Update Beschikbaar Versie {{ states('sensor.home_assistant_versions_dev')
        }}
  mode: single
- id: '1653126461264'
  alias: Schakelaar - Keuken Dubbel Keuken Lamp
  description: ''
  trigger:
  - platform: device
    domain: tasmota
    device_id: 4222716b45a1d39dbd565ee54535dac5
    type: button_double_press
    subtype: button_1
    discovery_id: D8F15BE77D0A_button_1_DOUBLE
  condition: []
  action:
  - type: toggle
    device_id: 4a2b72f0f45e6c51642e36d43ea5e32c
    entity_id: light.keuken
    domain: light
  mode: single
- id: '1653126790769'
  alias: Schakelaar - Santi Dubbel Rolluik
  description: ''
  trigger:
  - platform: device
    domain: tasmota
    device_id: b71563e3728141c6e5e649390681a7b7
    type: button_double_press
    subtype: button_1
    discovery_id: 2CF432C02815_button_1_DOUBLE
  condition: []
  action:
  - service: cover.toggle
    data: {}
    target:
      device_id: 4296f897a44538a9b541d1a2bc0a2295
  mode: single
- id: '1653126873228'
  alias: Schakelaar - Santi Hold Wled
  description: ''
  trigger:
  - platform: device
    domain: tasmota
    device_id: b71563e3728141c6e5e649390681a7b7
    type: button_long_press
    subtype: button_1
    discovery_id: 2CF432C02815_button_1_HOLD
  condition: []
  action:
  - type: toggle
    device_id: 37772b9b7040a174af7d0992802c61c7
    entity_id: light.wled_santi
    domain: light
  mode: single
- id: '1653202710748'
  alias: Verlichting - Motion Schuur
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.motion_schuur_occupancy
  condition:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  action:
  - choose:
    - conditions:
      - type: is_motion
        condition: device
        device_id: e9691606a8fc7b3264d331b130b254ea
        entity_id: binary_sensor.motion_schuur_occupancy
        domain: binary_sensor
      sequence:
      - service: light.turn_on
        data: {}
        target:
          entity_id: light.schuur_groep
    default:
    - service: light.turn_off
      data: {}
      target:
        entity_id: light.schuur_groep
  mode: single
- id: '1653407158347'
  alias: Remote - Overloop
  description: ''
  use_blueprint:
    path: EPMatt/ikea_e2001_e2002.yaml
    input:
      integration: Zigbee2MQTT
      controller_entity: sensor.remote_overloop_action
      helper_last_controller_event: input_text.helper_e2002
      action_button_left_short:
      - service: light.toggle
        data:
          brightness_pct: 100
        target:
          entity_id: light.zolder
      action_button_right_short:
      - type: toggle
        device_id: 164a63ca549c719a100c8ba6eeacc2c6
        entity_id: light.licht_elyza
        domain: light
      action_button_up_short:
      - service: cover.open_cover
        data: {}
        target:
          device_id: 8d114b3c9cfb890d35bc3e52db65cd6a
      action_button_down_short:
      - service: cover.close_cover
        data: {}
        target:
          device_id: 8d114b3c9cfb890d35bc3e52db65cd6a
      action_button_down_long:
      - type: toggle
        device_id: cec7ba9131e5a3caafa4305e8cce223e
        entity_id: light.wled_elyza
        domain: light
      action_button_up_long:
      - service: light.toggle
        data: {}
        target:
          entity_id: light.overloop
- id: '1653408286649'
  alias: Remote - Woonkamer
  description: ''
  use_blueprint:
    path: EPMatt/ikea_e1524_e1810.yaml
    input:
      integration: Zigbee2MQTT
      controller_entity: sensor.remote_woonkamer_action
      helper_last_controller_event: input_text.helper_e1810
      action_button_up_short:
      - type: toggle
        device_id: 4a2b72f0f45e6c51642e36d43ea5e32c
        entity_id: light.keuken
        domain: light
      action_button_center_short:
      - service: light.toggle
        data:
          brightness_pct: 75
        target:
          entity_id: light.woonkamer_spotjes
      - device_id: ''
        domain: ''
        entity_id: ''
- id: '1653409956101'
  alias: Remote - Woonkamer
  description: ''
  use_blueprint:
    path: EPMatt/ikea_e1524_e1810.yaml
    input:
      integration: Zigbee2MQTT
      controller_entity: sensor.remote_woonkamer_action
      helper_last_controller_event: input_text.helper_e1810
      action_button_left_short:
      - service: light.toggle
        data:
          brightness_pct: 100
        target:
          entity_id: light.tuin_lampen
      action_button_right_short:
      - service: light.toggle
        data:
          brightness_pct: 100
        target:
          entity_id: light.patio
      action_button_up_short:
      - type: toggle
        device_id: 4a2b72f0f45e6c51642e36d43ea5e32c
        entity_id: light.keuken
        domain: light
      action_button_center_short:
      - service: light.toggle
        data:
          brightness_pct: 100
        target:
          entity_id: light.woonkamer_spotjes
      action_button_down_short:
      - service: cover.toggle
        data: {}
        target:
          entity_id: cover.rolluiken
- id: '1653590844696'
  alias: Update notifications
  description: ''
  use_blueprint:
    path: mdegat01/update_notifications.yaml
    input:
      reminder_hours: '3'
      update_entities:
      - update.u7lt
      - update.dream_machine_pro
      - update.u7msh
      - update.us8p60
      - update.usmini
      - update.wled_elyza_firmware
      - update.wled_santi_firmware
      mobile_app_device: 9f035e104be4bcce4b3a992f3fb072d0
      send_to_ha: true
- id: '1653591806367'
  alias: Tag Gang is scanned
  description: ''
  trigger:
  - platform: tag
    tag_id: 1b2cf4c5-7e80-4b55-869b-de8b602617c6
  condition: []
  action:
  - type: toggle
    device_id: e5db3653dada9b0d11d0938e57e035b7
    entity_id: light.gang
    domain: light
  mode: single
