# Board: Generic ESP32 Board (Generic)
# Definition: definitions/boards/generic-esp32/manifest.yaml

esphome:
  name: test
  friendly_name: test

esp32:
  variant: esp32
  framework:
    type: esp-idf

logger:

api:
  encryption:
    key: "XIKWlkKwP/Zl/AVOU5DmPAQkspkV2smvBfwmtf7Df7k="

ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: test Fallback Hotspot
    password: "pYOkO1byMSAN"

captive_portal:
